// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vlvJbBAi-ujwwY1SS33kilW9qpCQneo',
    appId: '1:360109794071:web:5ee3e7eb004bc14f62cd52',
    messagingSenderId: '360109794071',
    projectId: 'todo-b5a1c',
    authDomain: 'todo-b5a1c.firebaseapp.com',
    storageBucket: 'todo-b5a1c.appspot.com',
    measurementId: 'G-K2MDD45KQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXj3dxT09APhowTkkGX8Gam-EzVeNt3hY',
    appId: '1:360109794071:android:2aea876b3dcc9b8262cd52',
    messagingSenderId: '360109794071',
    projectId: 'todo-b5a1c',
    storageBucket: 'todo-b5a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqpN7WmYezpnBbKBEY65D5vGsNXnremc',
    appId: '1:360109794071:ios:2d622d4449281f5462cd52',
    messagingSenderId: '360109794071',
    projectId: 'todo-b5a1c',
    storageBucket: 'todo-b5a1c.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqpN7WmYezpnBbKBEY65D5vGsNXnremc',
    appId: '1:360109794071:ios:86ce5eeeedf958b562cd52',
    messagingSenderId: '360109794071',
    projectId: 'todo-b5a1c',
    storageBucket: 'todo-b5a1c.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
